# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergies',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Foods'),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
        migrations.AlterField(
            model_name='dietplans',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Foods'),
        ),
        migrations.AlterField(
            model_name='dietplans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='muscle_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Muscles'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Muscles'),
        ),
        migrations.AlterField(
            model_name='supplementplans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
        migrations.AlterField(
            model_name='supplementplans',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Supplements'),
        ),
        migrations.AlterField(
            model_name='workoutplans',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Exercises'),
        ),
        migrations.AlterField(
            model_name='workoutplans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp2.Members'),
        ),
    ]
