# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='muscles',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
